<?php
$table_structure = array (
  'ccact_accounts' => 'CREATE TABLE `ccact_accounts` (
  `id` int(36) NOT NULL AUTO_INCREMENT,
  `created` datetime DEFAULT NULL,
  `description` text,
  `account_name` varchar(255) DEFAULT NULL,
  `account_num` varchar(255) DEFAULT NULL,
  `contact_name` varchar(64) DEFAULT NULL,
  `billing_address1` varchar(255) DEFAULT NULL,
  `billing_address2` varchar(255) DEFAULT NULL,
  `billing_city` varchar(255) DEFAULT NULL,
  `billing_state` varchar(2) DEFAULT NULL,
  `billing_zip` varchar(12) DEFAULT NULL,
  `billing_province` varchar(64) DEFAULT NULL,
  `billing_country` varchar(3) DEFAULT NULL,
  `billing_phone` varchar(32) DEFAULT NULL,
  `status` tinyint(4) DEFAULT \'0\',
  `legacy` tinyint(1) NOT NULL,
  `deleted` tinyint(2) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `account_name` (`account_name`),
  KEY `deleted` (`deleted`),
  KEY `account_num` (`account_num`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8',
  'ccact_accounts_edits' => 'CREATE TABLE `ccact_accounts_edits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `schedule_id` int(11) DEFAULT NULL,
  `calltype_id` int(11) DEFAULT NULL,
  `call_list_id` int(11) DEFAULT NULL,
  `file_id` int(11) DEFAULT NULL,
  `note_id` int(11) DEFAULT NULL,
  `messages_summary_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `user_id` int(11) NOT NULL,
  `user_username` varchar(32) NOT NULL,
  `description` text NOT NULL,
  `old_values` longtext,
  `new_values` longtext,
  `change_type` enum(\'delete\',\'edit\',\'add\',\'recover\') NOT NULL,
  `section` enum(\'account\',\'did\',\'employee\',\'custom\',\'calltype\',\'schedule\',\'oncall\',\'summary\',\'files\',\'employee_contact\',\'note\') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  KEY `created` (`created`),
  KEY `account_id` (`account_id`),
  KEY `call_list_id` (`call_list_id`),
  KEY `did_id` (`did_id`),
  KEY `employee_id_2` (`employee_id`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=latin1',
  'ccact_actions' => 'CREATE TABLE `ccact_actions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sort` tinyint(4) NOT NULL,
  `schedule_id` int(11) DEFAULT NULL,
  `action_text` text,
  `action_type` tinyint(4) DEFAULT \'0\' COMMENT \'1=TXF, 2=BLINDTXF, 3=TXTMSG, 4=EMAIL, 5=WEB6=VMAIL\',
  `action_url` varchar(255) DEFAULT NULL,
  `eid` text,
  `did_id` int(11) DEFAULT NULL,
  `helper` text,
  `inactive_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `flag` tinyint(1) DEFAULT \'0\',
  `inactive` tinyint(1) NOT NULL,
  `dispatch_only` tinyint(2) NOT NULL DEFAULT \'0\',
  `legacy` tinyint(1) NOT NULL,
  `legacy_type` varchar(16) DEFAULT NULL,
  `action_opt` varchar(4) DEFAULT NULL,
  `section` int(11) NOT NULL,
  `action_label` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`),
  KEY `account_id` (`did_id`),
  KEY `schedule_id` (`schedule_id`),
  KEY `inactive_ts` (`inactive_ts`)
) ENGINE=MyISAM AUTO_INCREMENT=46 DEFAULT CHARSET=latin1', 'ccact_sections' => 'CREATE TABLE `ccact_sections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sort` int(11) NOT NULL,
  `title` varchar(64) DEFAULT NULL,
  `schedule_id` int(11) NOT NULL,
  `section_action` int(11) NOT NULL,
  `section_num` int(11) NOT NULL,
  `calltype_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `schedule_id` (`schedule_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;', 'ccact_applications' => 'CREATE TABLE `ccact_applications` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `application` varchar(128) DEFAULT NULL,
  `url` text,
  `deleted` tinyint(1) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `legacy` tinyint(1) NOT NULL,
  `enabled` varchar(45) NOT NULL DEFAULT \'0\',
  `method` varchar(45) DEFAULT NULL,
  `trigger` varchar(45) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `username` varchar(45) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `account_id` (`account_id`),
  KEY `did_id` (`did_id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1',
  'ccact_application_parameters' => 'CREATE TABLE `ccact_application_parameters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sort` tinyint(4) DEFAULT NULL,
  `application_id` int(11) NOT NULL,
  `parameter` varchar(45) NOT NULL,
  `value` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`application_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_app_settings' => 'CREATE TABLE `ccact_app_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `field` varchar(255) NOT NULL,
  `value` varchar(512) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `field` (`field`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=latin1',
  'ccact_breaks' => 'CREATE TABLE `ccact_breaks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` int(11) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_bulletin_recipients' => 'CREATE TABLE `ccact_bulletin_recipients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bulletin_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `ack_ts` datetime DEFAULT \'0000-00-00 00:00:00\',
  PRIMARY KEY (`id`),
  KEY `bulletin_id` (`bulletin_id`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_bulletins' => 'CREATE TABLE `ccact_bulletins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by` int(11) NOT NULL,
  `note` text NOT NULL,
  `required` tinyint(4) DEFAULT \'0\' COMMENT \'if set to 1 user must acknowledge before proceeding\',
  `created_ts` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `required` (`required`),
  KEY `msg_grouping` (`created_by`,`created_ts`),
  KEY `created_ts` (`created_ts`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_call_events' => 'CREATE TABLE `ccact_call_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `call_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `extension` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `description` text NOT NULL,
  `level` tinyint(2) DEFAULT \'0\' COMMENT \'Visible to: 1=Customer, 10=Operator, 20=Manager, 30=Admin, 40=Superuser\',
  `event_type` smallint(6) DEFAULT NULL COMMENT \'1=Text, 2=Button Click, 3=Minder Click, 4=Msg edit,5=delivered, 6=undelivered\',
  `button_data` text,
  PRIMARY KEY (`id`),
  KEY `message_id` (`call_id`),
  KEY `created` (`created`),
  KEY `event_type` (`event_type`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1380 DEFAULT CHARSET=latin1',
  'ccact_call_lists' => 'CREATE TABLE `ccact_call_lists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `hide_from_operator` tinyint(2) NOT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `inactive` tinyint(2) NOT NULL DEFAULT \'0\',
  `legacy` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `account_id` (`account_id`),
  KEY `did_id` (`did_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_call_lists_schedules' => 'CREATE TABLE `ccact_call_lists_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `call_list_id` int(11) NOT NULL,
  `notes` text,
  `start_date` datetime DEFAULT NULL COMMENT \'Specific beginning date/ time, i.e June 29, 2002 11:23pm\',
  `end_date` datetime DEFAULT NULL,
  `start_day` int(6) unsigned DEFAULT NULL,
  `end_day` int(6) unsigned DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `instructions` text,
  `active` tinyint(1) DEFAULT \'1\',
  `check_days` tinyint(1) DEFAULT \'0\',
  `mon` tinyint(1) DEFAULT \'0\',
  `tue` tinyint(1) DEFAULT \'0\',
  `wed` tinyint(1) DEFAULT \'0\',
  `thu` tinyint(1) DEFAULT \'0\',
  `fri` tinyint(1) DEFAULT \'0\',
  `sat` tinyint(1) DEFAULT \'0\',
  `sun` tinyint(1) DEFAULT \'0\',
  `list_type` varchar(4) DEFAULT NULL COMMENT \'2=rotating\',
  `employee_ids` text,
  `effective_date` date DEFAULT NULL,
  `created` int(11) NOT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT \'0\',
  `deleted_ts` datetime NOT NULL,
  `legacy` tinyint(1) DEFAULT NULL,
  `legacy_list` text,
  PRIMARY KEY (`id`),
  KEY `call_list_id` (`call_list_id`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `start_day` (`start_day`),
  KEY `end_day` (`end_day`),
  KEY `did_id` (`did_id`),
  KEY `deleted` (`deleted`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_call_logs' => 'CREATE TABLE `ccact_call_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `did_number` varchar(16) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `extension` varchar(16) DEFAULT NULL,
  `queue` varchar(16) DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `wrapup_time` datetime NOT NULL,
  `cid_name` varchar(128) DEFAULT NULL,
  `cid_number` varchar(255) DEFAULT NULL,
  `unique_id` varchar(64) NOT NULL,
  `sip_call_id` varchar(128) DEFAULT NULL,
  `tag` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`),
  KEY `start_time` (`start_time`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=210 DEFAULT CHARSET=latin1',
  'ccact_call_logs_old' => 'CREATE TABLE `ccact_call_logs_old` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `did_number` varchar(16) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `extension` varchar(16) DEFAULT NULL,
  `queue` varchar(16) DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `wrapup_time` datetime NOT NULL,
  `cid_name` varchar(128) DEFAULT NULL,
  `cid_number` varchar(255) DEFAULT NULL,
  `unique_id` varchar(64) NOT NULL,
  `tag` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`),
  KEY `start_time` (`start_time`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_call_sipcallids' => 'CREATE TABLE `ccact_call_sipcallids` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `call_id` int(11) NOT NULL,
  `sipcallid` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `call_id` (`call_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1',
  'ccact_calltypes' => 'CREATE TABLE `ccact_calltypes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `type` varchar(255) DEFAULT NULL,
  `sort` tinyint(2) DEFAULT \'0\',
  `verbose` tinyint(1) NOT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `deleted` tinyint(2) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `legacy` tinyint(1) NOT NULL,
  `template` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `did_id` (`did_id`),
  KEY `deleted` (`deleted`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1',
  'ccact_cell_carriers' => 'CREATE TABLE `ccact_cell_carriers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `addr` varchar(50) NOT NULL,
  `sms` varchar(128) DEFAULT NULL,
  `mms` varchar(128) DEFAULT NULL,
  `rank` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `carriername` (`name`,`addr`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_cids' => 'CREATE TABLE `ccact_cids` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `number` varchar(32) NOT NULL,
  `name` varchar(64) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `number_name` (`number`,`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_company_audio' => 'CREATE TABLE `ccact_company_audio` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `company_audio` longblob,
  `company_audio_type` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_complaints' => 'CREATE TABLE `ccact_complaints` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `operator_id` int(11) NOT NULL,
  `category` varchar(255) NOT NULL,
  `category_other` varchar(255) DEFAULT NULL,
  `description` text,
  `created` datetime NOT NULL,
  `incident_date` datetime NOT NULL,
  `user_id` int(11) NOT NULL,
  `user_username` varchar(32) DEFAULT NULL,
  `user_ext` varchar(32) DEFAULT NULL,
  `message_id` int(11) DEFAULT NULL,
  `callers_name` varchar(255) NOT NULL,
  `investigation` text,
  `resolution` text,
  `status` tinyint(4) DEFAULT \'0\',
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `message_id` (`message_id`),
  KEY `operator_id` (`operator_id`),
  KEY `incident_date` (`incident_date`),
  KEY `status` (`status`),
  KEY `created` (`created`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_complaints_operators' => 'CREATE TABLE `ccact_complaints_operators` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `operator_id` int(11) NOT NULL,
  `complaint_id` int(11) NOT NULL,
  `operator_username` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_contacts' => 'CREATE TABLE `ccact_contacts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` int(11) NOT NULL,
  `contact_type` tinyint(4) DEFAULT NULL COMMENT \'1=phone,2=email,3=text,4=fax, 5=pager\',
  `data1` varchar(255) DEFAULT NULL,
  `data2` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_dashboard_users' => 'CREATE TABLE `ccact_dashboard_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password` varchar(64) NOT NULL,
  `name` varchar(32) NOT NULL,
  `extension` varchar(16) NOT NULL,
  `role` char(1) NOT NULL,
  `firstname` varchar(128) NOT NULL,
  `lastname` varchar(128) NOT NULL,
  `email` varchar(128) NOT NULL,
  `created` datetime DEFAULT NULL,
  `deleted` tinyint(4) NOT NULL,
  `deleted_ts` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `username` (`username`,`password`,`extension`),
  KEY `deleted` (`deleted`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_dialer_calls' => 'CREATE TABLE `ccact_dialer_calls` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `call_id` int(11) NOT NULL,
  `contact_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `call_id` (`call_id`,`contact_id`),
  KEY `contact_id` (`contact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1',
  'ccact_dialer_campaigns' => 'CREATE TABLE `ccact_dialer_campaigns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subacct_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `title` varchar(512) NOT NULL,
  `description` text NOT NULL,
  `calltype_id` int(11) NOT NULL,
  `deleted` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`subacct_id`),
  KEY `deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1',
  'ccact_dialer_contacts' => 'CREATE TABLE `ccact_dialer_contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone` varchar(32) NOT NULL,
  `extension` varchar(32) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `notes` text,
  `status` tinyint(4) NOT NULL,
  `created` datetime NOT NULL,
  `deleted` tinyint(4) NOT NULL,
  `deleted_ts` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1',
  'ccact_did_numbers' => 'CREATE TABLE `ccact_did_numbers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `status` tinyint(4) DEFAULT \'0\' COMMENT \'0=inactive,1=active\',
  `did_number` varchar(16) DEFAULT NULL,
  `industry` varchar(64) DEFAULT NULL,
  `alias_number` varchar(16) DEFAULT NULL,
  `difficulty` varchar(16) NOT NULL,
  `company` varchar(255) DEFAULT NULL,
  `company_visible` tinyint(1) NOT NULL,
  `businesstype` varchar(64) NOT NULL,
  `date_entered` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `modified_user_id` char(36) DEFAULT NULL,
  `created_by` char(36) DEFAULT NULL,
  `description` text,
  `assigned_user_id` char(36) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT \'1\',
  `contact_name` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address_visible` tinyint(1) NOT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(12) DEFAULT NULL,
  `province` varchar(64) DEFAULT NULL,
  `main_phone` varchar(16) DEFAULT NULL,
  `main_phone_visible` tinyint(1) NOT NULL,
  `main_fax` varchar(255) DEFAULT NULL,
  `main_fax_visible` tinyint(1) NOT NULL,
  `alt_phone` varchar(255) DEFAULT NULL,
  `alt_phone_visible` tinyint(1) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `website_visible` tinyint(1) NOT NULL,
  `hours` text,
  `hours_visible` tinyint(1) NOT NULL,
  `email` varchar(225) NOT NULL,
  `email_visible` tinyint(1) NOT NULL,
  `type` varchar(100) DEFAULT \'1\',
  `privacy` varchar(100) DEFAULT \'1\',
  `country` varchar(255) DEFAULT NULL,
  `answerphrase` varchar(255) DEFAULT NULL,
  `did_color` varchar(1) DEFAULT NULL,
  `has_oncall` tinyint(4) NOT NULL DEFAULT \'0\',
  `legacy` tinyint(1) DEFAULT NULL,
  `legacy_accountcode` varchar(16) DEFAULT NULL,
  `legacy_dispatch` text,
  `deleted` tinyint(2) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `legacy_multi_oncall` tinyint(1) DEFAULT NULL,
  `overflow` int(11) NOT NULL,
  `primary_or_overflow` tinyint(2) NOT NULL COMMENT \'0=primary,1=overflow\',
  `radio_advertising` tinyint(1) NOT NULL,
  `calls_per_day` smallint(6) NOT NULL,
  `calls_timing` varchar(32) DEFAULT NULL,
  `calls_timing_other` varchar(512) DEFAULT NULL,
  `service_sku` varchar(32) DEFAULT NULL,
  `email_format` tinyint(2) NOT NULL COMMENT \'0=html,1=text\',
  `email_subject_template` varchar(512) DEFAULT NULL,
  `include_cid` tinyint(2) NOT NULL,
  `exclude_prompts` tinyint(2) NOT NULL,
  `include_msg_id` tinyint(2) NOT NULL,
  `include_call_events` tinyint(2) NOT NULL,
  `scheduling_option` tinyint(4) NOT NULL,
  `advanced_setup` tinyint(4) NOT NULL,
  `billto_account` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `account_id` (`account_id`),
  KEY `did_number` (`did_number`),
  KEY `alias_number` (`alias_number`),
  KEY `legacy` (`legacy`),
  KEY `overflow` (`overflow`),
  KEY `status` (`status`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8',
  'ccact_did_numbers_entries' => 'CREATE TABLE `ccact_did_numbers_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `number` varchar(32) NOT NULL,
  `alias` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `number` (`number`),
  KEY `did_id` (`did_id`),
  KEY `alias` (`alias`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1',
  'ccact_ea_appointment_prompts' => 'CREATE TABLE `ccact_ea_appointment_prompts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `appointment_id` int(11) NOT NULL,
  `caption` varchar(1024) NOT NULL,
  `value` varchar(255) NOT NULL,
  `sort` smallint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `message_id` (`appointment_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_ea_appointments' => 'CREATE TABLE `ccact_ea_appointments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `call_id` int(11) NOT NULL,
  `confirmation` varchar(32) DEFAULT NULL,
  `customer_email` varchar(255) DEFAULT NULL,
  `book_datetime` datetime DEFAULT NULL,
  `start_datetime` datetime DEFAULT NULL,
  `end_datetime` datetime DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `notes` text,
  `hash` text,
  `is_unavailable` tinyint(4) DEFAULT \'0\',
  `id_users_provider` bigint(20) unsigned DEFAULT NULL,
  `id_users_customer` bigint(20) unsigned DEFAULT NULL,
  `id_services` bigint(20) unsigned DEFAULT NULL,
  `id_google_calendar` text,
  `user_id` int(11) NOT NULL,
  `deleted` int(11) NOT NULL,
  `delete_reason` text,
  PRIMARY KEY (`id`),
  KEY `id_services` (`id_services`),
  KEY `id_users_provider` (`id_users_provider`),
  KEY `call_id` (`call_id`),
  KEY `deleted` (`deleted`),
  KEY `confirmation` (`confirmation`),
  KEY `start_datetime` (`start_datetime`),
  KEY `end_datetime` (`end_datetime`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8',
  'ccact_ea_providers' => 'CREATE TABLE `ccact_ea_providers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` int(10) unsigned NOT NULL,
  `contact_id` varchar(255) DEFAULT NULL,
  `service_id` int(11) NOT NULL,
  `notification` tinyint(4) NOT NULL,
  `working_plan` text,
  `google_sync` tinyint(4) NOT NULL,
  `deleted` tinyint(4) NOT NULL,
  `deleted_ts` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_services` (`contact_id`),
  KEY `id_users` (`employee_id`,`contact_id`),
  KEY `service_id` (`service_id`),
  KEY `deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8',
  'ccact_ea_service_prompts' => 'CREATE TABLE `ccact_ea_service_prompts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `service_id` int(11) DEFAULT NULL,
  `ptype` int(11) DEFAULT NULL COMMENT \'1=text, 2=textarea, 3=select\',
  `options` text,
  `caption` varchar(512) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `maxchar` tinyint(3) unsigned NOT NULL,
  `required` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `action_id` (`service_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_ea_services' => 'CREATE TABLE `ccact_ea_services` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `name` varchar(256) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `currency` varchar(32) DEFAULT NULL,
  `description` text,
  `category` bigint(20) unsigned DEFAULT NULL,
  `offset_hours` int(11) NOT NULL,
  `slot_minutes` int(11) NOT NULL,
  `max_bookings` int(11) NOT NULL,
  `enable_delete` tinyint(2) NOT NULL,
  `enable_edit` tinyint(2) NOT NULL,
  `deleted` tinyint(4) NOT NULL,
  `deleted_ts` datetime DEFAULT NULL,
  `disable_conf_email` tinyint(2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_service_categories` (`category`),
  KEY `did_id` (`did_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8',
  'ccact_ea_services_providers' => 'CREATE TABLE `ccact_ea_services_providers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` int(20) unsigned NOT NULL,
  `contact_id` int(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_services` (`contact_id`),
  KEY `id_users` (`employee_id`,`contact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8',
  'ccact_emails' => 'CREATE TABLE `ccact_emails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `did_id` int(11) NOT NULL,
  `call_id` int(11) NOT NULL,
  `subject` text NOT NULL,
  `content_html` text NOT NULL,
  `content_text` text NOT NULL,
  `format` varchar(32) NOT NULL,
  `recipients` text NOT NULL,
  `processed` tinyint(2) NOT NULL COMMENT \'0=new,1=processed,2=failed\',
  `template` varchar(32) NOT NULL,
  `date_sent` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `processed` (`processed`),
  KEY `created` (`created`),
  KEY `did_id` (`did_id`),
  KEY `call_id` (`call_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_employees' => 'CREATE TABLE `ccact_employees` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `sort` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `title` varchar(128) DEFAULT NULL,
  `gender` tinyint(2) DEFAULT \'0\' COMMENT \'0=unknown, 1=female, 2=male\',
  `hide_hold` tinyint(1) NOT NULL DEFAULT \'0\',
  `hide_unsure` tinyint(1) NOT NULL DEFAULT \'0\',
  `special_instructions` text,
  `deleted` tinyint(1) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `legacy` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `account_id` (`account_id`),
  KEY `did_id` (`did_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1',
  'ccact_employees_contacts' => 'CREATE TABLE `ccact_employees_contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sort` tinyint(4) DEFAULT NULL,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `contact` varchar(255) NOT NULL,
  `contact_type` int(11) NOT NULL COMMENT \'1=phone, 2=cell, 3=email, 4=voicemail, 5=text, 6=web, 7=pager, 8=fax\',
  `primary` int(11) NOT NULL DEFAULT \'0\',
  `visible` tinyint(1) NOT NULL DEFAULT \'1\',
  `label` varchar(32) DEFAULT NULL,
  `options` text,
  `flag` tinyint(1) NOT NULL,
  `ext` varchar(10) DEFAULT NULL,
  `carrier` varchar(64) DEFAULT NULL,
  `carrier_id` int(11) DEFAULT NULL,
  `legacy` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`),
  KEY `did_id_2` (`did_id`),
  KEY `employee_id` (`employee_id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1',
  'ccact_faxes' => 'CREATE TABLE `ccact_faxes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `src_fax` varchar(14) NOT NULL,
  `dst_fax` varchar(25) NOT NULL,
  `created` datetime NOT NULL,
  `fax_processed` tinyint(2) NOT NULL COMMENT \'0=new,1=processed,2=failed\',
  `fax_processed_ts` datetime DEFAULT NULL,
  `fax_retry` smallint(6) NOT NULL,
  `fax_text` text,
  `fax_tif` longblob NOT NULL,
  `account_num` varchar(15) NOT NULL,
  `format` varchar(16) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `src_fax` (`src_fax`),
  KEY `dst_fax` (`dst_fax`),
  KEY `fax_processed` (`fax_processed`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_files' => 'CREATE TABLE `ccact_files` (
  `id` int(25) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `title` varchar(250) NOT NULL DEFAULT \'\',
  `file_name` varchar(250) NOT NULL DEFAULT \'\',
  `file_type` varchar(15) NOT NULL DEFAULT \'\',
  `file_size` varchar(45) NOT NULL DEFAULT \'\',
  `file_content` longblob NOT NULL,
  `file_extension` varchar(10) NOT NULL DEFAULT \'\',
  `created` datetime NOT NULL,
  `deleted` tinyint(2) NOT NULL,
  `deleted_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_keys' => 'CREATE TABLE `ccact_keys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `public_key` varchar(128) NOT NULL,
  `private_key` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `public_key` (`public_key`,`private_key`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_logins' => 'CREATE TABLE `ccact_logins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password` varchar(128) NOT NULL,
  `login_type` tinyint(3) NOT NULL,
  `subaccount_id` text,
  `employee_id` text,
  `account_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `account_id` (`account_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_messages' => 'CREATE TABLE `ccact_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `extension` int(11) NOT NULL,
  `call_id` int(11) NOT NULL,
  `schedule_id` int(11) DEFAULT NULL,
  `calltype` varchar(255) DEFAULT NULL,
  `calltype_id` int(11) DEFAULT NULL,
  `calltype_instructions` text,
  `notes` text,
  `created` datetime DEFAULT NULL,
  `active_ts` datetime DEFAULT NULL,
  `minder` tinyint(1) NOT NULL DEFAULT \'0\',
  `minder_ts` datetime NOT NULL,
  `unsure` tinyint(1) NOT NULL DEFAULT \'0\',
  `urgent` tinyint(1) NOT NULL DEFAULT \'0\',
  `instructions` text,
  `last_eid` int(11) NOT NULL,
  `delivered` tinyint(1) NOT NULL DEFAULT \'0\',
  `hold` tinyint(4) NOT NULL DEFAULT \'0\',
  `hold_until` datetime DEFAULT NULL,
  `audited` tinyint(1) NOT NULL,
  `summary_last_sent` datetime DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `audited_by` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `did_id` (`did_id`),
  KEY `call_id` (`call_id`),
  KEY `user_id` (`user_id`),
  KEY `audited` (`audited`),
  KEY `calltype` (`calltype`),
  KEY `created` (`created`),
  KEY `active_ts` (`active_ts`),
  KEY `delivered` (`delivered`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1',
  'ccact_messages_delivery' => 'CREATE TABLE `ccact_messages_delivery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `operator_id` int(11) NOT NULL,
  `delivery_name` varchar(255) DEFAULT NULL,
  `delivery_contact` varchar(255) DEFAULT NULL,
  `delivery_contact_id` text,
  `delivery_contact_label` varchar(32) NOT NULL,
  `delivered_time` datetime DEFAULT NULL,
  `delivered_by_userid` varchar(64) DEFAULT NULL,
  `delivered_by_ext` varchar(16) NOT NULL,
  `delivery_method` varchar(16) DEFAULT NULL,
  `delivered` tinyint(4) NOT NULL,
  `hold` tinyint(4) NOT NULL,
  `urgent` tinyint(4) NOT NULL,
  `employee_id` text,
  PRIMARY KEY (`id`),
  KEY `employee_id` (`employee_id`),
  KEY `message_id` (`message_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_messages_prompts' => 'CREATE TABLE `ccact_messages_prompts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `caption` varchar(1024) NOT NULL,
  `value` varchar(1024) NOT NULL,
  `sort` smallint(4) NOT NULL,
  `ptype` int(11) NOT NULL,
  `maxchar` int(11) NOT NULL,
  `required` tinyint(1) NOT NULL,
  `action_num` int(11) NOT NULL,
  `verification` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1',
  'ccact_messages_prompts_edits' => 'CREATE TABLE `ccact_messages_prompts_edits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `caption` varchar(1024) NOT NULL,
  `value` varchar(1024) NOT NULL,
  `sort` smallint(4) NOT NULL,
  `ptype` int(11) NOT NULL,
  `maxchar` int(11) NOT NULL,
  `required` tinyint(1) NOT NULL,
  `user_id` int(11) NOT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `edit_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_messages_summary' => 'CREATE TABLE `ccact_messages_summary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `did_tz` varchar(128) NOT NULL COMMENT \'automatically updated by DB trigger \'\'update_timezone\'\'\',
  `destination_email` varchar(512) NOT NULL,
  `destination_fax` varchar(512) NOT NULL,
  `employee_contact_ids` varchar(512) DEFAULT NULL,
  `all_day` tinyint(1) DEFAULT \'0\',
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `send_time` time DEFAULT NULL,
  `last_sent` datetime DEFAULT \'0000-00-00 00:00:00\',
  `last_run` datetime DEFAULT NULL,
  `active` tinyint(2) DEFAULT \'1\',
  `mon` tinyint(1) NOT NULL,
  `tue` tinyint(1) DEFAULT \'0\',
  `wed` tinyint(1) DEFAULT \'0\',
  `thu` tinyint(1) DEFAULT \'0\',
  `fri` tinyint(1) DEFAULT \'0\',
  `sat` tinyint(1) DEFAULT \'0\',
  `sun` tinyint(1) DEFAULT \'0\',
  `tx_interval` smallint(6) DEFAULT NULL COMMENT \'interval in minutes\',
  `msg_type` tinyint(4) DEFAULT NULL,
  `unreviewed` tinyint(1) NOT NULL,
  `no_message` tinyint(1) NOT NULL,
  `no_message_type` tinyint(4) NOT NULL,
  `no_message_send_time` time DEFAULT NULL,
  `no_message_last_sent` datetime DEFAULT \'0000-00-00 00:00:00\',
  `created` datetime NOT NULL,
  `deleted` tinyint(1) NOT NULL,
  `deleted_ts` datetime DEFAULT NULL,
  `legacy` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`),
  KEY `all_day` (`all_day`),
  KEY `start_time` (`start_time`),
  KEY `end_time` (`end_time`),
  KEY `send_time` (`send_time`),
  KEY `last_sent` (`last_sent`),
  KEY `active` (`active`),
  KEY `tx_interval` (`tx_interval`),
  KEY `mon` (`mon`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_messages_summary_log' => 'CREATE TABLE `ccact_messages_summary_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_summary_id` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `did_tz` varchar(128) NOT NULL COMMENT \'automatically updated by DB trigger \'\'update_timezone\'\'\',
  `destination_email` varchar(512) NOT NULL,
  `destination_fax` varchar(512) NOT NULL,
  `all_day` tinyint(1) DEFAULT \'0\',
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `send_time` time DEFAULT NULL,
  `last_sent` datetime DEFAULT \'0000-00-00 00:00:00\',
  `last_run` datetime DEFAULT NULL,
  `active` tinyint(2) DEFAULT \'1\',
  `mon` tinyint(1) DEFAULT \'0\',
  `tue` tinyint(1) DEFAULT \'0\',
  `wed` tinyint(1) DEFAULT \'0\',
  `thu` tinyint(1) DEFAULT \'0\',
  `fri` tinyint(1) DEFAULT \'0\',
  `sat` tinyint(1) DEFAULT \'0\',
  `sun` tinyint(1) DEFAULT \'0\',
  `tx_interval` smallint(6) DEFAULT NULL COMMENT \'interval in minutes\',
  `msg_type` tinyint(4) DEFAULT NULL,
  `unreviewed` tinyint(1) NOT NULL,
  `no_message` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `deleted` tinyint(1) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `legacy` tinyint(1) NOT NULL,
  `message_ids` text NOT NULL,
  `summary_sent` datetime NOT NULL,
  `summary_sent_to` text,
  `no_message_sent` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`),
  KEY `created` (`created`),
  KEY `last_run` (`last_run`),
  KEY `message_summary_id` (`message_summary_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_messages_summary_sent' => 'CREATE TABLE `ccact_messages_summary_sent` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `messages_summary_id` int(11) NOT NULL,
  `summary_last_sent` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`),
  KEY `summary_last_sent` (`summary_last_sent`),
  KEY `messages_summary_id` (`messages_summary_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_mistakes' => 'CREATE TABLE `ccact_mistakes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `did_id` int(11) NOT NULL,
  `category` varchar(255) NOT NULL,
  `category_other` varchar(255) DEFAULT NULL,
  `description` text,
  `created` datetime NOT NULL,
  `user_id` int(11) NOT NULL,
  `user_username` varchar(32) DEFAULT NULL,
  `user_ext` varchar(32) DEFAULT NULL,
  `message_id` int(11) DEFAULT NULL,
  `message_created` datetime NOT NULL,
  `mistake_recipient` smallint(11) NOT NULL,
  `recipient_username` varchar(64) DEFAULT NULL,
  `deleted` tinyint(2) NOT NULL,
  `deleted_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_userid` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `created` (`created`),
  KEY `message_id` (`message_id`),
  KEY `user_id` (`user_id`),
  KEY `message_created` (`message_created`),
  KEY `mistake_recipient` (`mistake_recipient`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_mms_carriers' => 'CREATE TABLE `ccact_mms_carriers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `addr` varchar(50) NOT NULL,
  `rank` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `carriername` (`name`,`addr`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_notes' => 'CREATE TABLE `ccact_notes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) DEFAULT NULL,
  `did_id` int(11) DEFAULT NULL,
  `description` text,
  `created` datetime NOT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_username` varchar(32) DEFAULT NULL,
  `user_ext` varchar(32) DEFAULT NULL,
  `message_id` int(11) DEFAULT NULL,
  `visible` tinyint(4) NOT NULL,
  `display_location` tinyint(4) NOT NULL,
  `bg_color` varchar(16) DEFAULT NULL,
  `extra_class` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `message_id` (`message_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_outbound' => 'CREATE TABLE `ccact_outbound` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `extension` varchar(64) DEFAULT NULL,
  `called_num` varchar(64) DEFAULT NULL,
  `created` datetime NOT NULL,
  `call_end` datetime DEFAULT NULL,
  `incoming_unique_id` varchar(64) NOT NULL,
  `did_id` int(11) NOT NULL,
  `call_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `did_id` (`did_id`),
  KEY `created` (`created`),
  KEY `user_id` (`user_id`),
  KEY `call_id` (`call_id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1',
  'ccact_overflow_centers' => 'CREATE TABLE `ccact_overflow_centers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_prompts' => 'CREATE TABLE `ccact_prompts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `action_id` int(11) DEFAULT NULL,
  `did_id` int(11) NOT NULL,
  `ptype` int(11) DEFAULT NULL COMMENT \'1=text, 2=textarea, 3=select\',
  `options` text,
  `caption` varchar(512) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `maxchar` int(10) unsigned NOT NULL,
  `required` tinyint(4) NOT NULL,
  `inactive` tinyint(1) NOT NULL,
  `legacy` int(11) NOT NULL,
  `verification` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `action_id` (`action_id`),
  KEY `did_id` (`did_id`)
) ENGINE=MyISAM AUTO_INCREMENT=112 DEFAULT CHARSET=latin1',
  'ccact_time_trackers' => 'CREATE TABLE `ccact_time_trackers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `did_id` int(11) NOT NULL,
  `activity_start` datetime NOT NULL,
  `activity_end` datetime NOT NULL,
  `activity_category` varchar(45) NOT NULL,
  `activity_type` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `created` (`created`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_queues' => 'CREATE TABLE `ccact_queues` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `queue` varchar(16) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `queue` (`queue`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1',
  'ccact_schedules' => 'CREATE TABLE `ccact_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `did_id` int(11) NOT NULL,
  `calltype_id` int(11) DEFAULT NULL,
  `start_date` datetime DEFAULT NULL COMMENT \'Specific beginning date/ time, i.e June 29, 2002 11:23pm\',
  `end_date` datetime DEFAULT NULL,
  `start_day` int(6) unsigned DEFAULT NULL,
  `end_day` int(6) unsigned DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `instructions` text,
  `active` tinyint(2) DEFAULT \'1\',
  `check_days` tinyint(1) DEFAULT \'0\',
  `mon` tinyint(1) DEFAULT \'0\',
  `tue` tinyint(1) DEFAULT \'0\',
  `wed` tinyint(1) DEFAULT \'0\',
  `thu` tinyint(1) DEFAULT \'0\',
  `fri` tinyint(1) DEFAULT \'0\',
  `sat` tinyint(1) DEFAULT \'0\',
  `sun` tinyint(1) DEFAULT \'0\',
  `type` varchar(8) DEFAULT NULL,
  `show_employee_picker` tinyint(2) DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `created` datetime NOT NULL,
  `legacy` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted` (`deleted`),
  KEY `calltype_id` (`calltype_id`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `end_day` (`end_day`),
  KEY `did_id` (`did_id`),
  KEY `account_id` (`account_id`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=latin1',
  'ccact_sms_carriers' => 'CREATE TABLE `ccact_sms_carriers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `addr` varchar(50) NOT NULL,
  `rank` int(11) NOT NULL,
  `prefix` text,
  PRIMARY KEY (`id`),
  KEY `carriername` (`name`,`addr`)
) ENGINE=MyISAM AUTO_INCREMENT=234 DEFAULT CHARSET=latin1',
  'ccact_user_groups' => 'CREATE TABLE `ccact_user_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `user_ids` text NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1',
  'ccact_user_log' => 'CREATE TABLE `ccact_user_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `type` enum(\'login\',\'logout\',\'break\',\'start_shift\',\'end_shift\',\'taking_calls\',\'not_taking_calls\',\'leave_break\',\'not_taking_calls_btn\',\'taking_calls_btn\',\'refresh_browser\') DEFAULT NULL,
  `log_type` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `extension` varchar(16) NOT NULL,
  `break_reason` varchar(255) DEFAULT NULL,
  `break_end` datetime DEFAULT NULL,
  `session` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created` (`created`),
  KEY `user_id` (`user_id`),
  KEY `extension` (`extension`)
) ENGINE=MyISAM AUTO_INCREMENT=588 DEFAULT CHARSET=latin1',
  'ccact_users' => 'CREATE TABLE `ccact_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password` varchar(64) NOT NULL,
  `role` char(1) NOT NULL,
  `firstname` varchar(128) NOT NULL,
  `lastname` varchar(128) NOT NULL,
  `email` varchar(128) NOT NULL,
  `account_id` int(11) DEFAULT NULL,
  `subaccount_id` text,
  `employee_id` text,
  `created` datetime DEFAULT NULL,
  `deleted` tinyint(4) DEFAULT \'0\',
  `deleted_ts` datetime DEFAULT NULL,
  `operator` tinyint(4) DEFAULT NULL,
  `display_stat` tinyint(2) DEFAULT NULL,
  `alias` varchar(64) DEFAULT NULL,
  `monitor` tinyint(2) DEFAULT NULL,
  `add_account_notes` tinyint(2) DEFAULT NULL,
  `photo` longblob,
  PRIMARY KEY (`id`),
  KEY `username` (`username`,`password`),
  KEY `deleted` (`deleted`),
  KEY `display_stat` (`display_stat`),
  KEY `monitor` (`monitor`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1',
  'ccact_users_queues' => 'CREATE TABLE `ccact_users_queues` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `queue` varchar(255) NOT NULL,
  `penalty` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `operator_id` (`user_id`,`queue`),
  KEY `queue` (`queue`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1',
  'ccact_welcome_msgs' => 'CREATE TABLE `ccact_welcome_msgs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `note` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1',
  'ccact_sections' => 'CREATE TABLE `ccact_sections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sort` int(11) NOT NULL,
  `title` varchar(64) DEFAULT NULL,
  `schedule_id` int(11) NOT NULL,
  `section_action` int(11) NOT NULL COMMENT \'0=end here, 1= go to section specified in \'\'section_num\'\'\',
  `section_num` int(11) NOT NULL,
  `calltype_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `schedule_id` (`schedule_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3939 DEFAULT CHARSET=latin1',
);
?>